import { 
  Check, 
  ChevronLeft, 
  ChevronRight, 
  ChevronsUpDown, 
  Circle, 
  ClipboardList, 
  Clock, 
  Calendar, 
  X, 
  Loader2, 
  Plus, 
  Search, 
  Filter, 
  LogOut, 
  Settings, 
  User, 
  Bell, 
  Inbox, 
  CheckSquare, 
  ListTodo, 
  Users, 
  LayoutDashboard, 
  Smartphone, 
  BarChart4,
  Edit,
  AlertCircle,
  Trash
} from "lucide-react";

export const Icons = {
  clipboard: ClipboardList, // Corrected the icon reference
  close: X,
  spinner: Loader2,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  chevronsUpDown: ChevronsUpDown,
  check: Check,
  circle: Circle,
  add: Plus,
  search: Search,
  filter: Filter,
  logout: LogOut,
  settings: Settings,
  user: User,
  bell: Bell,
  inbox: Inbox,
  tasks: CheckSquare,
  todo: ListTodo,
  users: Users,
  dashboard: LayoutDashboard,
  mobile: Smartphone,
  chart: BarChart4,
  clock: Clock,
  calendar: Calendar,
  alert: AlertCircle,
  edit: Edit,
  trash: Trash,
  logo: ClipboardList,
};
